name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: odysseus
          POSTGRES_PASSWORD: odysseus_password
          POSTGRES_DB: odysseus_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true

    - name: Check formatting
      run: cargo fmt --all -- --check

    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Run tests
      run: cargo test --all-features --workspace
      env:
        DATABASE_URL: postgres://odysseus:odysseus_password@localhost:5432/odysseus_db

    - name: Build release
      run: cargo build --release --workspace

    - name: Upload binary artifacts
      uses: actions/upload-artifact@v4
      with:
        name: users-service-${{ github.sha }}
        path: target/release/users
        retention-days: 30

  docker:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Convert repository owner to lowercase
      id: lowercase
      run: echo "owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

    - name: Build and push users-service
      uses: docker/build-push-action@v5
      with:
        context: .
        file: services/users/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ steps.lowercase.outputs.owner }}/odysseus-users:latest
          ghcr.io/${{ steps.lowercase.outputs.owner }}/odysseus-users:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
